# Generated by Django 5.0.2 on 2024-02-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debts', models.FloatField(default=0.0)),
                ('zugew_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ausgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beschreibung', models.CharField(max_length=50)),
                ('Preis', models.FloatField(default=0.0)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGIdeeApp.person')),
            ],
        ),
    ]
