# Generated by Django 4.2.6 on 2023-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WGIdeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ausgabe',
            old_name='description',
            new_name='Beschreibung',
        ),
        migrations.RenameField(
            model_name='ausgabe',
            old_name='person',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='ausgabe',
            old_name='value',
            new_name='Preis',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
