# Generated by Django 5.0.2 on 2024-02-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGIdeeApp', '0002_rename_description_ausgabe_beschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='Person',
            field=models.CharField(max_length=50),
        ),
    ]
