# Generated by Django 5.0.2 on 2024-02-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGIdeeApp', '0002_alter_ausgabe_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGIdeeApp.person'),
        ),
    ]
