# Generated by Django 5.0.2 on 2024-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGIdeeApp', '0005_remove_person_wert'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='debts',
            field=models.FloatField(default=0.0),
        ),
    ]
