# Generated by Django 5.0.2 on 2024-03-05 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGIdeeApp', '0006_alter_ausgabe_ausgabedatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='Ausgabedatum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
